============================= test session starts ==============================
platform linux -- Python 3.9.19, pytest-7.3.2, pluggy-1.4.0
rootdir: /triton/python
plugins: shard-0.1.2, flakefinder-1.1.0, cpp-2.3.0, xdist-3.3.1, hypothesis-5.35.1, xdoctest-1.1.0, rerunfailures-14.0
collected 1 item
Running 1 items in this shard

python/test/unit/hopper/test_flashattention.py F

=================================== FAILURES ===================================
____________________________ test_op[4-48-2048-64] _____________________________

Z = 4, H = 48, N_CTX = 2048, D_HEAD = 64, dtype = torch.float16

    @pytest.mark.parametrize('Z, H, N_CTX, D_HEAD', [
        (4, 48, 128, 64),
        (4, 48, 256, 64),
        (4, 48, 512, 64),
        (4, 48, 1024, 64),
        (4, 48, 2048, 64),
        (4, 48, 4096, 64),
        #  (4, 48, 8192, 64), out of memory
    ])
    @pytest.mark.skipif(torch.cuda.get_device_capability()[0] < 9, reason="requires arch 9+")
    def test_op(Z, H, N_CTX, D_HEAD, dtype=torch.float16):
        g = torch.manual_seed(20)
>       q = torch.empty((Z, H, N_CTX, D_HEAD), dtype=dtype, device="cuda").normal_(mean=0.1, std=0.2, generator=g).requires_grad_()
E       RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

python/test/unit/hopper/test_flashattention.py:373: RuntimeError
=========================== short test summary info ============================
FAILED python/test/unit/hopper/test_flashattention.py::test_op[4-48-2048-64] - RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
============================== 1 failed in 1.95s ===============================
